name: Build EXE and APP for Windows and macOS

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build EXE on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .exe using PyInstaller
        run: |
          pyinstaller --onefile autoMouseFree.py

      - name: List dist folder
        run: dir dist

      - name: Zip EXE file
        run: Compress-Archive -Path dist\autoMouseFree.exe -DestinationPath bot-windows.zip

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-windows
          path: bot-windows.zip

  build-mac:
    name: Build APP on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .app using PyInstaller
        run: |
          pyinstaller --onefile autoMouseFree.py

      - name: Zip APP file
        run: |
          cd dist
          zip -r ../bot-mac.zip autoMouseFree

      - name: Upload APP artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-mac
          path: bot-mac.zip
