name: Build for Windows and macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pynput  # หรือ pip install -r requirements.txt ถ้ามีไฟล์นี้

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build Windows EXE
        run: pyinstaller autoMouseFree.py --onefile --noconsole --name bot

      - name: Zip EXE
        run: Compress-Archive -Path dist\bot.exe -DestinationPath bot-windows.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-windows
          path: bot-windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build macOS APP
        run: pyinstaller autoMouseFree.py --windowed --name autoMouseFree

      - name: Zip macOS App
        run: |
          ditto -c -k --sequesterRsrc --keepParent dist/autoMouseFree.app bot-macos.zip

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-macos
          path: bot-macos.zip
